version: '3'

services:
  myDB:
    image: mysql:8.0
    container_name: vivero-database
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=adminadmin
      - MYSQL_DATABASE=vivero_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=adminadmin
    volumes:
      - ./mysql:/var/lib/mysql
